name: "Hello World workflow" # This is the name of the workflow or this the name of the pipleline

# Controls when the action will run. Event to trigger the pipeline. In this case, the pipeline will be triggered when a push is done to main or production branch.
on:
  push:
    branches:
      - main
      - production

# Jobs are the steps that are executed in the pipeline. In this case, there is only one job called hello_world.
jobs:
  hello_world: # This is the name of the job
    runs-on: ubuntu-latest # Type of machine to run this job on the machine that will execute the job
    steps:
      - name: "Print Hello World" # name of the step
        run: echo "Hello, world!" # to define what should happen in this step we use run key

      - name: "Print current date"
        run: date
