name: "Hello World workflow" # This is the name of the workflow

# Controls when the action will run. Triggers the workflow on push done to master or production branch
on:
  push:
    branches:
      - main
      - production

jobs:
  hello_world: # This is the name of the job
    runs-on: ubuntu-latest # Type of machine to run this job on
    steps:
      - name: "Print Hello World" # name of the step
        run: echo "Hello, world!" # to define what should happen in this step we use run key

