name: "Multiple Event Pipeline"

on:
  push: # Event: Whenever a push is made to the repository on the master/test branch.
    branches:
      - main
      - test
  pull_request: # Event: Whenever a pull request is made to the repository on the main/test branch.
    branches:
      - main
  workflow_dispatch: # Event: Whenever a workflow is manually triggered. There will be a button to trigger the pipeline in the github actions page.

jobs:
  on-push: # Job name
    if: github.event_name == 'push' # this condition is used to run the job only when the event is a push
    runs-on: ubuntu-latest 
    steps:
      - name: "Running on master/test push"
        run: echo "Tunning on master/test push"

  on-pull-request: # Job name
    if: github.event_name == 'pull_request' # this condition is used to run the job only when the event is a pull request
    runs-on: ubuntu-latest
    steps:
      - name: "Running on main pull request"
        run: echo "Tunning on main pull request"