name: 'workflow trigger when we push to any branch'

# Controls when the action will run. Triggers the workflow on push to any branch
on:
  push:
    branches:
      - '**'  # This triggers on any branch

jobs:
  build:
    runs-on: ubuntu-latest  # Type of machine to run this job on
    steps:
    
      - name: Print workflow information # name of the step
        run: |
          echo "Repository: ${{ github.repository }}"  # Prints the repository name in format owner/repo-name
          echo "Commit SHA: ${{ github.sha }}"  # Prints the full commit SHA (hash) that triggered this workflow
          echo "Actor: ${{ github.actor }}"  # Prints the GitHub username of the person who triggered this workflow